exclude:
  - "/vendor/"

title: Anna Jacobson # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I am an engineer by training, project manager by experience, and data scientist by aspiration. I am passionate about the evolution of decisions, from data to information to insight to action - and I'm fascinated by the potential this process has to change the world around us.
  <br><br> 
  <a href="https://www.linkedin.com/in/anna-ching-jacobson/">LinkedIn</a> | <a href="https://www.behance.net/annacjacobson">Behance</a> | 
  <a href="https://medium.com/@annacjacobson">Medium</a> | <a href="https://www.flickr.com/photos/27309894@N02/with/48581980482/">Flickr</a> 
  <br><br> 
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
