exclude:
  - "/vendor/"

title: Anna C. Jacobson # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
<p>An nineteen-year veteran of the architecture, engineering, and construction (AEC) industry, I have collaborated on some of
the most complex and culturally significant new projects in Southern California. I started my career at Morley Builders, an
ENR Top 400 general contractor based in Santa Monica. In 2005 I became one of the youngest project managers in the
company’s 70-year history.</p>
<br><br>
<p>After more than a decade of hands-on field experience, I recognized a need for a more comprehensive approach to project
planning, earlier in the project life-cycle. Working directly with the heads of Estimating, Operations, and Human Resources, I
developed a new position – Senior Preconstruction Manager – to address this need. In this role, I provide leadership and
direction in all phases of preconstruction. I engage with new and existing clients to secure opportunities, provide technical
expertise and oversight in estimating, and perform other preconstruction functions including proposal and interview
preparation, scheduling, BIM coordination, and design and constructability reviews. My leadership and organization,
communication skills, passion for detail, and dedication to outstanding service have allowed me to excel in executing
complicated, high-quality, and unique projects.</p>
<br><br>
<p>As the focus of my career has shifted from on-site management to project planning, I have become fascinated with the vast
potential for data to fundamentally transform the way we create buildings. I believe that the AEC industry is rapidly
approaching an inflection point in its trajectory where the traditional, instinct-driven decision-making processes will give
way to more data-informed, analytic approaches. My goal is to help develop and lead the exciting changes ahead.</p>

  <br><br>
  <a href="https://www.linkedin.com/in/anna-ching-jacobson/">LinkedIn</a>
  <br><br>
  <a href="https://www.behance.net/annacjacobson">Behance</a>
  <br><br>
  <a href="https://medium.com/@annacjacobson">Medium</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
