exclude:
  - "/vendor/"

title: Anna Jacobson # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
  <br><br>
  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  <br><br>
  <a href="https://www.linkedin.com/in/anna-ching-jacobson/">LinkedIn</a>
  <a href="https://www.behance.net/annacjacobson">Behance</a>
  <a href="https://medium.com/@annacjacobson">Medium</a> 
  <a href="https://www.flickr.com/photos/27309894@N02/with/48581980482/">Flickr</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
